### ISSUE TITLE
Homework assignments for week 1 completed

### ISSUE THREAD

**Issue by arnoldbugingo** [cven5873-ss23/website#3]
@larnsce I am super thrilled to have the opportunity to learn some programming languages like R and the rest. Will access to the languages be given to me only throughout the duration of the course or can I still have access to them even after the course - especially seeing that some have to be purchased to carry the licenses?

Another quick one, @larnsce, will access to GitHub be revoked after the course or can this carry on even after the course?

Thanks

**Comment by larnsce** [comment]
Hi @arnoldbugingo. Thanks for working through the assignments. I am thrilled to get the opportunity to introduce you to these tools. :) 

In summary:

- Your access to the course material on Posit Cloud will remain after the course
- You will need to install the open source (and free) versions of R & RStudio IDE on your computer to continue working with it
- Access to GitHub and all material that is in the GitHub Organisation for the course will be available to you after the course

In my teaching, I only use software tools that are open and accessible without the need to buy any licenses. We use Posit Cloud, so that I have a controlled computing environment for teaching. 

If you have any follow-up questions, let me know. 

I will close this issue to mark it as "done".

**Comment by arnoldbugingo** [comment]
Perfect! Thanks for the response @larnsce. I totally appreciate your guidance

**Comment by larnsce** [comment]
Hi @arnoldbugingo, I am sharing a reference to an issue of another participant to also inform you about the Posit Primers: https://github.com/cven5873-ss23/website/issues/4#issuecomment-1578032287
